version: '3'

services:
  backend:
    build: .
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
